import esbuild from 'esbuild';
import builtins from 'builtin-modules';
import obsidianPlugin from 'esbuild-plugin-obsidian';
import { execSync } from 'child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const PRODUCTION = (process.argv[2] === 'production');

esbuild.build({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  platform: 'node',
  target: 'es2020',
  logLevel: "info",
  sourcemap: PRODUCTION ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js', // Output to dist directory
  plugins: [obsidianPlugin()],
}).then(() => {
  // Copy sql-wasm.wasm to dist after build
  execSync('cp node_modules/sql.js/dist/sql-wasm.wasm dist/');
  console.log('Copied sql-wasm.wasm to dist/');
}).catch(() => process.exit(1));
